/*
 * This file is generated by jOOQ.
*/
package com.gov.train.common.joop;


import com.gov.train.common.joop.tables.Account;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = com.gov.train.common.joop.tables.Account.ACCOUNT;
}
